version: "3"
name: "maraidb-starter"
services:
  mariadb:
    image: mariadb:10.10.2
    restart: always
    expose:
      - ${MYSQL_TCP_PORT}
    ports:
      - "${HOST_PORT}:${MYSQL_TCP_PORT}"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./log:/var/log