version: "3.7"
services:
  auth-mariadb:
    container_name: mariadb1
    image: mariadb:10.10.2
    restart: always
    expose:
      - ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./log:/var/log
    networks:
      - default
      - django-auth-network

networks:
  django-auth-network:
    driver: bridge
    external: true
